const gulp = require('gulp');
const rename = require('gulp-rename');

// Task to rename index.umd.js to chart.umd.js
gulp.task('rename-umd', function () {
  return gulp.src('lib/index.umd.js') // Source file generated by rollup
    .pipe(rename('hcc_line_chart.umd.js'))    // Rename action
    .pipe(gulp.dest('lib'));          // Destination folder (overwrites or places next to it)
});